<body bgcolor=orange>
<form>
<a href="3.php" target=ewan3><input type=button value=HOME class=sign></a>
<a href=games.php target=ewan3><input type=button value=GAMES class=sign></a>
<a href="logout.php" target=ewan3><input type=button value=LOGOUT class=sign></a>
<style>
input.sign {
    width: 150px;
	height: 30px;
    color: red;
    text-transform: uppercase;
    text-shadow: blue 1px 1px;
    border-top: 1px solid #ad64e0;
    margin-top: 10px;
 
    /*** Adding CSS3 Gradients ***/
    background: -webkit-gradient(linear, 0% 0%, 0% 100%, from(greenyellow), to(yellow));
    background:  -moz-linear-gradient(19% 75% 90deg,greenyellow, yellow);
}
</style>
