<html>

<head>

<title>First Val's WEB LOGOUT</title>

<style>

body {

  background:url('blac.png') ;

  color:greenyellow;

  font-size: 0.8em;

  font-family:Arial, sans-serif;

  margin:10% 32.5%;

  }

a:link,active {

color:#8fc9ed;

font-size: 14px;

text-decoration:none;

font-family: Arial, sans-serif;

}



a:visited{

color:#8fc9ed;

}



a:hover {

color:white;

font-family: Arial, sans-serif;

}



table {

border:0px;

padding:1px;

background:url('Hexo_Backgrounds_2_By_Art-Styles_1920X1200.jpg');

-moz-border-radius: 5px;

-webkit-border-radius: 5px;

}



table td {

padding:3px;

background:url('Best-top-desktop-hd-wall-wood-wallpaper-wood-wallpapers-wall-picture-image-30.jpg');

-moz-border-radius: 5px;

-webkit-border-radius: 5px;

}



</style>

</head>

<body><meta HTTP-EQUIV="Refresh" CONTENT="4;">

<table border=0 width=500>
<tr><td><img src=hamtaro_g_004.gif>
<tr><td><center>Message<tr><td>

You have been logout... <br>Please wait you're currently redirecting to the main page.<br><a href="http://dbbabon.comoj.com/exam/firstval.html" target=23525256236>click here</a> if you want to redirect manually.

</table>

</body>

</html>
